version: 1.1.2
cache: true
registration:
  socialLogins:
    - discord
    - facebook
    - github
    - google
    - openid
endpoints:
  custom:
    - name: Zanity
      apiKey: user_provided
      baseURL: https://api.zanity.xyz/v1
      models:
        default:
          - gpt-3.5-turbo
          - gpt-3.5-turbo-0125
          - gpt-4o
          - gpt-4o-unfiltered
          - o1-mini
          - o1-preview
          - gpt-4o-2024-08-06
          - gpt-4o-2024-05-13
          - gpt-4o-mini
          - gpt-4o-mini-2024-07-18
          - chatgpt-4o-latest
          - gpt-4
          - gpt-4-0613
          - gpt-4-1106-preview
          - gpt-4-1106-vision-preview
          - gpt-4-turbo-2024-04-09
          - gpt-4-turbo
          - llama-2-7b-chat
          - llama-2-13b-chat
          - llama-3-8b-instruct
          - llama-3-70b-instruct
          - llama-3.1-8b-instruct
          - llama-3.1-70b-instruct
          - llama-3.1-nemotron-70b
          - llama-3.1-405b-instruct
          - llama-3.1-sonar-small-128k-online
          - llama-3.1-sonar-large-128k-online
          - llama-3.1-sonar-huge-128k-online
          - llama-3.1-sonar-small-128k-chat
          - llama-3.1-sonar-large-128k-chat
          - llama-3.2-1b-instruct
          - llama-3.2-3b-instruct
          - llama-3.2-90b-vision-instruct
          - llama-3.2-11b-vision-instruct
          - gemini-1.5-flash-latest
          - gemini-1.5-pro-latest
          - gemini-1.5-experimental
          - nemotron-4-340b
          - claude-3-haiku
          - claude-3-sonnet
          - claude-3-opus
          - claude-3.5-sonnet
          - claude-3-5-haiku-20241022
          - claude-3-5-sonnet-20241022
          - claude-2.1
          - qwen-max-0428
          - yi-large-preview
          - yi-large
          - yi-1.5-34b-chat
          - phi-3
          - phi-3-small-8k-instruct
          - phi-3-mini-4k-instruct
          - reka-core
          - reka-flash
          - reka-flash-online
          - command-r-plus
          - command-r-plus-08-2024
          - command-plus-08-2024
          - command-r
          - gemma-1.1-7b-it
          - gemma-1.1-2b-it
          - codestral
          - mistral-large-2402
          - mistral-medium
          - glm-4
          - glm-4-0116
          - dbrx-instruct
          - zephyr-141b
          - olmo-7b-instruct
          - vicuna-13b
          - openhermes-2.5-mistral-7b
          - hermes-3-llama-3.1-70b
          - hermes-3-llama-3.1-405b
          - mistral-large-2407
          - mistral-large
          - grok-2
          - llava-1.5-7b
          - mistral-7b-instruct-v0.1
          - mistral-7b-instruct-v0.2
          - mistral-7b-instruct-v0.3
          - mixtral-8x7B-instruct
          - mixtral-8x22b-instruct
          - gemma-2-9b-it
          - gemma-2-27b-it
          - gemma-7b-it
          - qwen1.5-1.8b-chat
          - qwen1.5-4b-chat
          - qwen1.5-7b-chat
          - qwen2-72b-instruct
          - qwen1.5-110b-chat
          - deepseek-coder-6.7b
          - discolm-german-7b
          - mistral-7b-instruct-v0.1-awq
          - zephyr-7b-beta
          - dolphin-2.9.1-llama-3-70b
          - nous-hermes-llama2
          - toppy-m-7b
          - dolphin-mixtral-8x7b
          - l3-70b-euryale-v2.1
          - lzlv_70b_fp16
          - WizardLM-2-7B
          - WizardLM-2-8x22B
          - openchat-3.5
          - openchat-3.6-8b
          - grok-fun
          - phi-2
          - phi-3-medium-4k-instruct
          - sqlcoder-7b-2
          - tinyllama-1.1b-chat
          - una-cybertron-7b
          - qwen2-vl-7b-instruct
          - qwen2-vl-72b-instruct
          - qwen2.5-72b-instruct
          - deepseek-v2.5
          - pixtral-12b-2409
          - yandexgpt-3-pro
          - gigachat-pro
          - gigachat-plus
          - gigachat
          - gigarp-alpha
          - gigarp-beta
          - reflection-70b
          - zanityrp-smol
          - airoboros-70b
          - magnum-12b
        fetch: true
      titleConvo: true
      titleModel: llama-3.1-8b-instruct
      summarize: false
      summaryModel: llama-3.1-8b-instruct
      forcePrompt: false
      dropParams: []
      iconURL: >-
        https://cdn.discordapp.com/icons/1268484294779736065/fb280e01dae7d8f210de2099b8cbd908.webp
      modelDisplayLabel: Zanity
