version: 1.1.2
cache: true
registration:
  socialLogins:
    - discord
    - facebook
    - github
    - google
    - openid
endpoints:
  custom:
    - name: Zanity
      apiKey: user_provided
      baseURL: https://api.zanity.xyz/v1
      models:
        default:
          - llama-3.1-8b-instruct
          - gpt-4o-mini
          - gpt-4o
          - claude-3.5-sonnet
          - llama-3.1-70b-instruct
          - o1-mini
        fetch: true
      titleConvo: true
      titleModel: llama-3.1-8b-instruct
      summarize: false
      summaryModel: llama-3.1-8b-instruct
      forcePrompt: false
      dropParams: []
      iconURL: >-
        https://cdn.discordapp.com/icons/1268484294779736065/fb280e01dae7d8f210de2099b8cbd908.webp
      modelDisplayLabel: Zanity